#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server.

apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get -y update
apt-get -y install haproxy

sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sed -i -e '$a\listen balancer\n\tbind :80\n\tbalance roundrobin\n\tserver web-01 54.174.113.81:80 check\n\tserver web-02 52.23.177.104:80 check\n' /etc/haproxy/haproxy.cfg
service haproxy restart
