#!/usr/bin/env bash
# Displays numbers from 1 to 100 in list format.
#   show Buzz" when the number is a multiple of 5.
#   Otherwise, displays the number.

for cnt in {1..100}
do
  if (( cnt % 3 == 0 && cnt % 5 == 0 ))
  then
    echo "FizzBuzz"
  elif (( cnt % 3 == 0 ))
  then
    echo "Fizz"
  elif (( cnt % 5 == 0 ))
  then
    echo "Buzz"
  else
    echo "$cnt"
  fi
done

