#!/usr/bin/env bash
# This sript shows time for 12 horus and 59 minutes.
#   Prints hours from 0 to 12
#   Prints minutes from 1 to 59

cnt=0

while [ $cnt -le 12 ]
do
	echo "Hour: $cnt"
	min=1
	while [ $min -le 59 ]
	do
		echo "$min"
		(( min++ ))
	done
	(( cnt++ ))
done
